### ISSUE TITLE
Trouble connecting to Oracle via Nodejs worker threads

### ISSUE THREAD

**Issue by PrabhuRathnavel** [oracle/node-oracledb#1300]
1. What versions are you using?
Oracle 11g Release 2 
  process.platform: win32
  process.version: v12.16.3
  process.arch: x64
  oracledb.versionString: 5.0.0
  oracledb.oracleClientVersionString: 11.2.0.2.0

2. Describe the problem
I'm using Nodejs' **worker_threads** to run scheduled jobs that need to connect to the db to pull data and perform certain tasks. For the worker threads to connect to the db, initially I tried to send a connection (that I obtained from a pool used by the main thread) to the worker thread via **workerData** but it threw _DOMException [DataCloneError]_. Seems like it is not possible to send db connections from main thread to worker.

Next I tried to create a new _non-pooled_ connection for worker thread (in addition to a connection pool that was created and used by the main thread) using the code mentioned below. But that resulted in below error.

**ORA-24550: signal received: Unhandled exception: Code=c0000005 Flags=0**

**kpedbg_dmp_stack()+428<-kpeDbgCrash()+102<-kpeDbgSignalHandler()+121<-skgesig_Win_UnhandledExceptionFilter()+173<-00007FFFC4D2BDC0<-00007FFFC8943167<-00007FFFC892B5E6<-00007FFFC893F7DD<-00007FFFC88AD856<-00007FFFC893E70E<-00007FFFB277251A<-00007FFFB2770E0D<-00007FFFB2749C01<-00007FFFB273A239<-00007FFFB2739F0B<-00007FFFB2724E22<-00007FF6EB8EDA2E<-00007FF6EB8DAF8D<-00007FF6EC5978C0<-00007FFFC6994034<-00007FFFC8913691**

I also tried adding code to create a _named_ connection pool for worker threads (while the main thread used the _default_ pool), but whenever the application tried to create the second pool (named one) it just crashed right away with no error in the console.

I have been trying to make the worker threads connect to Oracle db, but nothing worked so far and now I'm just stuck with no other option to try out. I would really appreciate it if you could provide me some inputs on how to connect to Oracle using worker threads.

3. Include a runnable Node.js script that shows the problem.
```
const oracledb = require('oracledb');
const { isMainThread } = require('worker_threads');
const { dbConfig } = require('../config/database.js');

//this method is invoked during application startup to create default pool for 'main' thread
const initialize = async() => {
  try {
    await oracledb.createPool(dbConfig);
  }
  catch (err) {
    console.log("Error initializing OTSS database..: "+ err);
  }
}

//method used by both main & worker threads to execute sqls
const simpleExecute = async (statement, binds = {}, opts = {}) => {
  return new Promise(async (resolve, reject) => {
    let conn;
    let result = {};
    opts.outFormat = oracledb.OBJECT;
    opts.autoCommit = true;

    try {
       //If the current thread is 'main' get a connection from the 'default' pool
      if(isMainThread) {
        conn = await oracledb.getConnection();
      }
      else {
        //if it is a worker-thread get a non-pooled conn.
        conn = await oracledb.getConnection({
          user: dbConfig.user,
          password: dbConfig.password,
          connectString: dbConfig.connectString
        });
      }
      result = await conn.execute(statement, binds, opts);
      resolve(result);
    }
    catch (err) {
      reject(err);
    }
    finally {
      if (conn) {
        try {
          //Put the connection back in the pool
          await conn.close();
        }
        catch (err) {
          console.log(err);
        }
      }
    }
  });
}
```

Thank you!

**Comment by anthony-tuininga** [comment]
I put together a complete runnable script:

```
const oracledb = require('oracledb');
const { Worker, isMainThread } = require('worker_threads');

const dbConfig = {
  user: "nodejs",
  password: "dev",
  connectString: "localhost/DB21PDB1"
};

async function performQuery() {
  console.log("Performing query: main thread?", isMainThread);
  const conn = await oracledb.getConnection(dbConfig);
  const result = await conn.execute("select sysdate from dual");
  console.log("Result:", result);
  await conn.close();
  console.log("Completed query...");
}

async function run() {
  await performQuery();
  if (isMainThread) {
    const worker = new Worker(__filename);
    worker.on("exit", (code) => {
      console.log("worker finished with exit code", code);
    });
  }
}

run();
```

Interestingly, on Linux this works fine with Node.js 12.16.3, but segfaults with 12.18.3! It also works fine with Node.js 12.18.4, though, and Node.js 14.11. That suggests this is a Node.js bug and updating your version of Node.js should resolve the issue.

**Comment by cjbj** [comment]
@anthony-tuininga didn't we think that a single connection pool probably wouldn't be shareable across threads?

**Comment by anthony-tuininga** [comment]
I just tried it with a pool as well and it works fine:

```
const oracledb = require('oracledb');
const { Worker, isMainThread } = require('worker_threads');

const dbConfig = {
  user: "nodejs",
  password: "dev",
  connectString: "localhost/orclpdb"
};

async function performQuery() {
  console.log("Performing query: main thread?", isMainThread);
  const conn = await oracledb.getConnection();
  const result = await conn.execute("select sysdate from dual");
  console.log("Result:", result);
  await conn.close();
  console.log("Completed query...");
}

async function run() {
  await oracledb.createPool(dbConfig);
  await performQuery();
  if (isMainThread) {
    const worker = new Worker(__filename);
    worker.on("exit", (code) => {
      console.log("worker finished with exit code", code);
    });
  }
}

run();
```

**Comment by anthony-tuininga** [comment]
I don't know, however, if this approach works under stress or not. And as has been noted by the worker API documentation, unless the worker is compute intensive there probably isn't much benefit to using it.

**Comment by PrabhuRathnavel** [comment]
Hi Anthony, thanks much for taking a look at this. I really appreciate the quick response.

I just tried updating Nodejs to 12.18.4, but the problem still persists. Same error. Please note, my requirement is to get a new pooled (or non-pooled connection) for a worker thread to connect to db "in addition" to an existing connection pool that is created during app startup and used by the main thread. Can you please test this scenario and let me know if I'm missing something.

Everything works fine when the main thread alone performs db operations using the connection from the pool, the problem happens only when a worker thread attempts to create a new connection, either non-pooled or a new named pool.

**Comment by anthony-tuininga** [comment]
Did you try both of my examples, modifying the connection parameters appropriately? If those work but yours does not, please supply a complete running example so I can try it myself. Thanks!

**Comment by PrabhuRathnavel** [comment]
I tried but whenever the worker thread attempted to create a new connection, the app just crashed right away.

**Comment by anthony-tuininga** [comment]
With my examples? Which version(s) of Node.js? Try with version 14.11 in particular. Try with a newer client. Try on Linux instead of Windows. I do see the crash with some versions of Node.js on Linux which suggests that it is a Node.js issue that has been corrected in more recent versions. @pvenkatraman may be able to try my examples on Windows.

**Comment by PrabhuRathnavel** [comment]
Yes, with your example. But, you know what something really strange just started to happen. As you asked about my Node version, I added below console.log statements to the _run()_ method in your first example to make sure I'm on the right Nodejs version that you suggested, all of a sudden the code started to work as expected (trust me I'm not high or something, it really happened)

`````
  console.log("process.platform: "+ process.platform);
  console.log("process.version: "+ process.version);
  console.log("process.arch: "+ process.arch);
  console.log("oracledb.versionString: "+ oracledb.versionString);
  console.log("oracledb.oracleClientVersionString: "+ oracledb.oracleClientVersionString);
````` 
This is the output I got after adding the above lines. 
`````
process.platform: win32
process.version: v12.18.4
process.arch: x64
oracledb.versionString: 5.0.0
oracledb.oracleClientVersionString: 11.2.0.2.0
Performing query: main thread? true
Result: {
  metaData: [ { name: 'SYSDATE' } ],
  rows: [ [ 2020-09-18T18:05:59.000Z ] ]
}
Completed query...
process.platform: win32
process.version: v12.18.4
process.arch: x64
oracledb.versionString: 5.0.0
oracledb.oracleClientVersionString: 2130988449.652.-959706367.396.932971697
Performing query: main thread? false
Result: {
  metaData: [ { name: 'SYSDATE' } ],
  rows: [ [ 2020-09-18T18:05:59.000Z ] ]
}
Completed query...
worker finished with exit code 0
`````
**But it DIDN'T work consistently though!** When I tried to run your code mulitple times, though it worked most of the times, I got the below error in between in the console too..
`````
Performing query: main thread? false
error: Error: DPI-1049: symbol OCIDefineByPos2 not found in OCI library
Completed query...
worker finished with exit code 0
`````

.. and this is what I see in the console, if I remove those console.logs. The app just stops for a couple of seconds when the worker thread tries to connect to db and then the app crashes without any error.
``````
Performing query: main thread? true
Result: {
  metaData: [ { name: 'SYSDATE' } ],
  rows: [ [ 2020-09-18T18:20:00.000Z ] ]
}
Completed query...
Performing query: main thread? false
``````

**Comment by PrabhuRathnavel** [comment]
The db is on my local machine. I don't have a Linux machine to test this out right now. Perhaps, I will give v14.11 a try, meanwhile could you check my above test results and see what could have caused the said behavior. Thanks!

**Comment by PrabhuRathnavel** [comment]
Tried Node v14.11, but same issue.

**Comment by anthony-tuininga** [comment]
@pvenkatraman, can you try on Windows?

@PrabhuRathnavel, can you set the environment variable `DPI_DEBUG_LEVEL` to the value 4 and see what you get? The error `DPI-1049: symbol OCIDefineByPos2 not found in OCI library` should never happen -- so that suggests some sort of corruption is in play, especially if the error is not consistent. I'm not seeing what you're seeing...but I am on a different platform and using a newer Oracle Client as well (11.2 is rather old). Are you using 11.2 on the server as well?

**Comment by pvenkatraman** [comment]
@anthony-tuininga here is the output I see:
C:\WORK\SRC\oracledb\b30182919\dataaccess_node-oracledb>node examples\issue1300.js
Performing query: main thread? true
Result: {
  metaData: [ { name: 'SYSDATE' } ],
  rows: [ [ 2020-09-21T21:17:29.000Z ] ]
}
Completed query...
Performing query: main thread? false

**Comment by PrabhuRathnavel** [comment]
@anthony-tuininga yes, I'm 11.2 on the server too.

After setting DPI_DEBUG_LEVEL = 4 this is what I see in the console when the worker thread is executed.

````
Performing query: main thread? false
17:06:05.135: fn start dpiContext_initConnCreateParams(00000239509FBA90)
ODPI [18160] 2020-09-22 17:06:05.152: fn end dpiContext_initConnCreateParams(00000239509FBA90) -> 0
ODPI [18160] 2020-09-22 17:06:05.160: fn start dpiContext_initCommonCreateParams(00000239509FBA90)
ODPI [18160] 2020-09-22 17:06:05.169: fn end dpiContext_initCommonCreateParams(00000239509FBA90) -> 0
ODPI [18160] 2020-09-22 17:06:05.176: fn start dpiConn_create(00000239509FBA90)
ODPI [18160] 2020-09-22 17:06:05.243: fn end dpiConn_create(00000239509FBA90) -> 0
ODPI [18160] 2020-09-22 17:06:05.248: fn start dpiConn_setStmtCacheSize(00000239524DA860)
ODPI [18160] 2020-09-22 17:06:05.256: fn end dpiConn_setStmtCacheSize(00000239524DA860) -> 0
ODPI [07656] 2020-09-22 17:06:05.265: fn start dpiConn_prepareStmt(00000239524DA860)
ODPI [07656] 2020-09-22 17:06:05.271: fn end dpiConn_prepareStmt(00000239524DA860) -> 0
ODPI [07656] 2020-09-22 17:06:05.278: fn start dpiStmt_getInfo(00000239526CCD10)
ODPI [07656] 2020-09-22 17:06:05.287: fn end dpiStmt_getInfo(00000239526CCD10) -> 0
ODPI [07656] 2020-09-22 17:06:05.294: fn start dpiStmt_execute(00000239526CCD10)
ODPI [07656] 2020-09-22 17:06:05.302: fn end dpiStmt_execute(00000239526CCD10) -> 0
ODPI [07656] 2020-09-22 17:06:05.308: fn start dpiStmt_getQueryInfo(00000239526CCD10)
ODPI [07656] 2020-09-22 17:06:05.316: fn end dpiStmt_getQueryInfo(00000239526CCD10) -> 0
ODPI [12480] 2020-09-22 17:06:05.325: fn start dpiConn_newVar(00000239524DA860)
ODPI [12480] 2020-09-22 17:06:05.331: fn end dpiConn_newVar(00000239524DA860) -> 0
ODPI [12480] 2020-09-22 17:06:05.338: fn start dpiStmt_define(00000239526CCD10)
ODPI [12480] 2020-09-22 17:06:05.345: fn end dpiStmt_define(00000239526CCD10) -> -1
ODPI [12480] 2020-09-22 17:06:05.352: fn start dpiStmt_release(00000239526CCD10)
ODPI [12480] 2020-09-22 17:06:05.359: fn end dpiStmt_release(00000239526CCD10) -> 0
error: Error: DPI-1049: symbol OCIDefineByPos2 not found in OCI library
ODPI [02244] 2020-09-22 17:06:05.369: fn start dpiConn_close(00000239524DA860)
ODPI [02244] 2020-09-22 17:06:05.379: fn end dpiConn_close(00000239524DA860) -> 0
ODPI [22112] 2020-09-22 17:06:05.387: fn start dpiConn_release(00000239524DA860)
ODPI [22112] 2020-09-22 17:06:05.392: fn end dpiConn_release(00000239524DA860) -> 0
Completed query...
ODPI [22112] 2020-09-22 17:06:05.402: fn start dpiContext_destroy(00000239509FBA90)
ODPI [22112] 2020-09-22 17:06:05.425: fn end dpiContext_destroy(00000239509FBA90) -> 0
worker finished with exit code 0
ODPI [09968] 2020-09-22 17:06:05.453: fn start dpiContext_destroy(00000239524BA630)
ODPI [09968] 2020-09-22 17:06:05.460: fn end dpiContext_destroy(00000239524BA630) -> 0
````

**Comment by PrabhuRathnavel** [comment]
@anthony-tuininga Looks like @pvenkatraman was able to reproduce the issue on Windows. From the output he posted I could see that the app had just stopped when a worker thread attempted to open a db connection.

**Comment by pvenkatraman** [comment]
Tried with DPI_DEBUG_LEVEL=4 and here is the output:

C:\WORK\SRC\oracledb\b30182919\dataaccess_node-oracledb>node examples\issue1300.js
ODPI [01584] 2020-09-22 17:26:23.507: ODPI-C 4.1.0-dev
ODPI [01584] 2020-09-22 17:26:23.510: debugging messages initialized at level 4
Performing query: main thread? true
ODPI [01584] 2020-09-22 17:26:23.522: fn start dpiContext_createWithParams
ODPI [01584] 2020-09-22 17:26:24.233: fn end dpiContext_createWithParams -> 0
ODPI [20720] 2020-09-22 17:26:24.238: fn start dpiContext_initConnCreateParams(000001FF19915980)
ODPI [20720] 2020-09-22 17:26:24.241: fn end dpiContext_initConnCreateParams(000001FF19915980) -> 0
ODPI [20720] 2020-09-22 17:26:24.247: fn start dpiContext_initCommonCreateParams(000001FF19915980)
ODPI [20720] 2020-09-22 17:26:24.253: fn end dpiContext_initCommonCreateParams(000001FF19915980) -> 0
ODPI [20720] 2020-09-22 17:26:24.257: fn start dpiConn_create(000001FF19915980)
ODPI [20720] 2020-09-22 17:26:26.924: fn end dpiConn_create(000001FF19915980) -> 0
ODPI [20720] 2020-09-22 17:26:26.929: fn start dpiConn_setStmtCacheSize(000001FF1986A800)
ODPI [20720] 2020-09-22 17:26:26.932: fn end dpiConn_setStmtCacheSize(000001FF1986A800) -> 0
ODPI [22964] 2020-09-22 17:26:26.937: fn start dpiConn_prepareStmt(000001FF1986A800)
ODPI [22964] 2020-09-22 17:26:26.941: fn end dpiConn_prepareStmt(000001FF1986A800) -> 0
ODPI [22964] 2020-09-22 17:26:26.946: fn start dpiStmt_getInfo(000001FF198B84D0)
ODPI [22964] 2020-09-22 17:26:26.949: fn end dpiStmt_getInfo(000001FF198B84D0) -> 0
ODPI [22964] 2020-09-22 17:26:26.952: fn start dpiStmt_execute(000001FF198B84D0)
ODPI [22964] 2020-09-22 17:26:27.201: fn end dpiStmt_execute(000001FF198B84D0) -> 0
ODPI [22964] 2020-09-22 17:26:27.206: fn start dpiStmt_getQueryInfo(000001FF198B84D0)
ODPI [22964] 2020-09-22 17:26:27.209: fn end dpiStmt_getQueryInfo(000001FF198B84D0) -> 0
ODPI [17780] 2020-09-22 17:26:27.214: fn start dpiConn_newVar(000001FF1986A800)
ODPI [17780] 2020-09-22 17:26:27.218: fn end dpiConn_newVar(000001FF1986A800) -> 0
ODPI [17780] 2020-09-22 17:26:27.220: fn start dpiStmt_define(000001FF198B84D0)
ODPI [17780] 2020-09-22 17:26:27.224: fn end dpiStmt_define(000001FF198B84D0) -> 0
ODPI [17780] 2020-09-22 17:26:27.227: fn start dpiStmt_setFetchArraySize(000001FF198B84D0)
ODPI [17780] 2020-09-22 17:26:27.229: fn end dpiStmt_setFetchArraySize(000001FF198B84D0) -> 0
ODPI [17780] 2020-09-22 17:26:27.233: fn start dpiStmt_fetchRows(000001FF198B84D0)
ODPI [17780] 2020-09-22 17:26:27.236: fn end dpiStmt_fetchRows(000001FF198B84D0) -> 0
ODPI [17780] 2020-09-22 17:26:27.239: fn start dpiStmt_release(000001FF198B84D0)
ODPI [17780] 2020-09-22 17:26:27.242: fn end dpiStmt_release(000001FF198B84D0) -> 0
ODPI [01584] 2020-09-22 17:26:27.245: fn start dpiVar_release(000001FF198B8410)
ODPI [01584] 2020-09-22 17:26:27.250: fn end dpiVar_release(000001FF198B8410) -> 0
Result: {
  metaData: [ { name: 'SYSDATE' } ],
  rows: [ [ 2020-09-21T23:26:27.000Z ] ]
}
ODPI [14640] 2020-09-22 17:26:27.256: fn start dpiConn_close(000001FF1986A800)
ODPI [14640] 2020-09-22 17:26:27.607: fn end dpiConn_close(000001FF1986A800) -> 0
ODPI [01584] 2020-09-22 17:26:27.610: fn start dpiConn_release(000001FF1986A800)
ODPI [01584] 2020-09-22 17:26:27.614: fn end dpiConn_release(000001FF1986A800) -> 0
Completed query...
ODPIPerforming query: main thread? false
 [26960] 2020-09-22 17:26:27.691: fn start dpiContext_createWithParams
ODPI [26960] 2020-09-22 17:26:27.695: fn end dpiContext_createWithParams -> 0
ODPI [20720] 2020-09-22 17:26:27.697: fn start dpiContext_initConnCreateParams(000001FF197EC0E0)
ODPI [20720] 2020-09-22 17:26:27.701: fn end dpiContext_initConnCreateParams(000001FF197EC0E0) -> 0
ODPI [20720] 2020-09-22 17:26:27.706: fn start dpiContext_initCommonCreateParams(000001FF197EC0E0)
ODPI [20720] 2020-09-22 17:26:27.710: fn end dpiContext_initCommonCreateParams(000001FF197EC0E0) -> 0
ODPI [20720] 2020-09-22 17:26:27.713: fn start dpiConn_create(000001FF197EC0E0)
ODPI [20720] 2020-09-22 17:26:29.949: fn end dpiConn_create(000001FF197EC0E0) -> 0
ODPI [20720] 2020-09-22 17:26:29.953: fn start dpiConn_setStmtCacheSize(000001FF1986A330)
ODPI [20720] 2020-09-22 17:26:29.956: fn end dpiConn_setStmtCacheSize(000001FF1986A330) -> 0
ODPI [22964] 2020-09-22 17:26:29.961: fn start dpiConn_prepareStmt(000001FF1986A330)
ODPI [22964] 2020-09-22 17:26:29.964: fn end dpiConn_prepareStmt(000001FF1986A330) -> 0
ODPI [22964] 2020-09-22 17:26:29.967: fn start dpiStmt_getInfo(000001FF198B8AD0)
ODPI [22964] 2020-09-22 17:26:29.975: fn end dpiStmt_getInfo(000001FF198B8AD0) -> 0
ODPI [22964] 2020-09-22 17:26:29.978: fn start dpiStmt_execute(000001FF198B8AD0)
ODPI [22964] 2020-09-22 17:26:30.227: fn end dpiStmt_execute(000001FF198B8AD0) -> 0
ODPI [22964] 2020-09-22 17:26:30.231: fn start dpiStmt_getQueryInfo(000001FF198B8AD0)
ODPI [22964] 2020-09-22 17:26:30.234: fn end dpiStmt_getQueryInfo(000001FF198B8AD0) -> 0
ODPI [17780] 2020-09-22 17:26:30.238: fn start dpiConn_newVar(000001FF1986A330)

**Comment by PrabhuRathnavel** [comment]
Hi @anthony-tuininga, I was wondering if you had a chance to take a look at the console outputs that I and @pvenkatraman posted above. Please let me know if you need any additional info to analyze this further.

**Comment by cjbj** [comment]
@PrabhuRathnavel be forewarned that this is a not a scenario in the test plan and not something we've really investigated.
