### ISSUE TITLE
Unable to install node-oracledb on Windows 10

### ISSUE THREAD

**Issue by sarath47** [oracle/node-oracledb#483]
#### Answer the following questions:
1. What error(s) you are seeing?
   C:\SAN\XXX\node_modules\oracledb>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\....\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
   Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
   C:\SVN\SmartMon\node_modules\oracledb\build\oracledb.vcxproj(20,3): error MSB4019: The imported project "C:\Microsoft.Cpp.Default.props" was not found. Conf
   irm that the path in the <Import> declaration is correct, and that the file exists on disk.
   gyp ERR! build error
   gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
   gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
   gyp ERR! stack     at emitTwo (events.js:87:13)
   gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
   gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
   gyp ERR! System Windows_NT 10.0.10586
   gyp ERR! command "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" "rebuild"
   gyp ERR! cwd C:\SVN\SmartMon\node_modules\oracledb
   gyp ERR! node -v v4.4.3
   gyp ERR! node-gyp -v v3.3.1
   gyp ERR! not ok
   npm ERR! Windows_NT 10.0.10586
   npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install" "oracledb"
   npm ERR! node v4.4.3
   npm ERR! npm  v2.15.1
   npm ERR! code ELIFECYCLE

npm ERR! oracledb@1.10.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the oracledb@1.10.1 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the oracledb package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs oracledb
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls oracledb
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\SVN\SmartMon\npm-debug.log
1. What _exact_ command caused the problem (e.g. what command did you try to install with)?  Who were you logged in as?
   npm install oracledb 
2. What environment variables did you set?  How _exactly_ did you set them?
   Set Path variables for oracle instant client , python v 2.7, installed, downloaded Microsoft VC++ redestibutable 2015 from 
   https://www.microsoft.com/en-us/download/details.aspx?id=48145

Set the following values in command prompt as I was getting ssl issue earlier
set NODE_TLS_REJECT_UNAUTHORIZED=0
set OCI_LIB_DIR=C:\Oracle\instantclient\sdk\lib\msvc
set OCI_INC_DIR=C:\Oracle\instantclient\sdk\include
1. What is your version of Node.js?
   v4.4.3
2. What is your version of the Oracle client (e.g. Instant Client)?  How was it installed?  Where it is installed?
   Extracted instant client zip under C:\Oracle added to path variable.
3. What is your OS and version?
   Windows 10
4. What compiler version did you use?

**Comment by bmrainc** [comment]
## i have the same question
## i install oracledb on window10 with Visual Studio2015,also i have set OCI_LIB_DIR and OCI_INC_DIR,the error like this:
![image](https://cloud.githubusercontent.com/assets/7332588/17612660/3374a4b6-6087-11e6-9e83-c6c2d4140b89.png)
## It seem that : “oci.h”: No such file or directory
## can you help me!

**Comment by snake2501** [comment]
I have a similar issue

this is my log, and my npm_debug
[npm-debug.txt](https://github.com/oracle/node-oracledb/files/415751/npm-debug.txt)

:

D:\GIT_FERRO\NodeJsWebApplication>set OCI_LIB_DIR=C:\Oracle\instantclient\instan
tclient_12_1\sdk\lib\msvc^V

D:\GIT_FERRO\NodeJsWebApplication>set OCI_INC_DIR=C:\Oracle\instantclient\instan
tclient_12_1\sdk\include

D:\GIT_FERRO\NodeJsWebApplication>path
PATH=C:\Program Files (x86)\MSBuild\14.0\bin\amd64;C:\Program Files (x86)\Micros
oft Visual Studio 14.0\VC\BIN\amd64;C:\Windows\Microsoft.NET\Framework64\v4.0.30
319;C:\Windows\Microsoft.NET\Framework64\;C:\Program Files (x86)\Windows Kits\8.
1\bin\x64;C:\Program Files (x86)\Windows Kits\8.1\bin\x86;C:\Oracle\Middleware-1
0.3.5\wlserver_10.3\server\native\win\32;C:\Windows\system32;C:\Windows;C:\Windo
ws\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x
86)\Intel\OpenCL SDK\2.0\bin\x86;C:\Program Files (x86)\Intel\OpenCL SDK\2.0\bin
\x64;C:\Program Files\TortoiseSVN\bin;C:\Java\jrockit-jdk1.6.0_45-R28.2.7-4.1.0\
bin;C:\Program Files\TortoiseGit\bin;C:\Program Files\nodejs\;C:\Program Files\G
it\cmd;C:\Python27;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance T
oolkit\;C:\Oracle\instantclient\instantclient_12_1;C:\Users\cmferrov\AppData\Roa
ming\npm

D:\GIT_FERRO\NodeJsWebApplication>npm install oracledb

> oracledb@1.10.1 install D:\GIT_FERRO\NodeJsWebApplication\node_modules\oracled
b
> node-gyp rebuild


D:\GIT_FERRO\NodeJsWebApplication\node_modules\oracledb>if not defined npm_confi
g_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\
..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
Los proyectos de esta solución se van a compilar de uno en uno. Para habilitar l
a compilación en paralelo, agregue el modificador "/m".
MSBUILD : error MSB3428: No se pudo cargar el componente "VCBuild.exe" de Visua
l C++. Para corregir este problema, 1) instale .NET Framework 2.0 SDK, 2) insta
le Microsoft Visual Studio 2005 o 3) agregue la ubicación del componente a la r
uta de acceso del sistema si está instalado en otro lugar.  [D:\GIT_FERRO\NodeJ
sWebApplication\node_modules\oracledb\build\binding.sln]
gyp ERR! build error
gyp ERR! stack Error: `msbuild` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\
npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces
s.js:204:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodej
s\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\GIT_FERRO\NodeJsWebApplication\node_modules\oracledb
gyp ERR! node -v v6.3.0
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "oracledb"
npm ERR! node v6.3.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE

npm ERR! oracledb@1.10.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the oracledb@1.10.1 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the oracledb package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs oracledb
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls oracledb
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\GIT_FERRO\NodeJsWebApplication\npm-debug.log

D:\GIT_FERRO\NodeJsWebApplication>

**Comment by peterremec** [comment]
I have a similar problem when installing node-oracledb:

```
> oracledb@1.11.0 install C:\Users\pr\AppData\Roaming\npm\node_modules\ora
cledb
> node-gyp rebuild


C:\Users\pr\AppData\Roaming\npm\node_modules\oracledb>if not defined npm_c
onfig_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\
\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )

Building the projects in this solution one at a time. To enable parallel build,
please add the "/m" switch.
C:\Users\pr\AppData\Roaming\npm\node_modules\oracledb\build\oracledb.vcxp
roj(20,3): error MSB4019: The imported project "C:\Microsoft.Cpp.Default.props"
 was not found. Confirm that the path in the <Import> declaration is correct, a
nd that the file exists on disk.
gyp ERR! build error
gyp ERR! stack Error: `msbuild` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\
npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces
s.js:204:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodej
s\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\pr\AppData\Roaming\npm\node_modules\oracledb
gyp ERR! node -v v6.4.0
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "oracledb" "-g"
npm ERR! node v6.4.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE

npm ERR! oracledb@1.11.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the oracledb@1.11.0 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the oracledb package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs oracledb
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls oracledb
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\pr\Development\Visual Studio 2013\npm-debug.log
```

Using node v6.4.0, VS 2013, Windows 8.1 pro, Oracle Instant Client 12.1.0.2.0.

**Comment by bmrainc** [comment]
oh,my god!Anyone help us?I cannot install it at all.

**Comment by bchr02** [comment]
You could try my fork which has has oracledb precompiled. Instructions here: https://github.com/oracle/node-oracledb/issues/18

**Comment by bchr02** [comment]
If you would rather compile yourself, there is a new npm tool from Microsoft that allows you to install the build tools with a simple one line command. Also, I have created a simple npm module for downloading the proper instantclient files using a one line command followed by answering a few prompts. 

Here are the steps:

npm install --global npm
npm install --global --production windows-build-tools
set PATH=%cd%\instantclient;%PATH%
set OCI_LIB_DIR=%cd%\instantclient\sdk\lib\msvc
set OCI_INC_DIR=%cd%\instantclient\sdk\include
npm install instantclient

**Comment by bmrainc** [comment]
@bchr02 thank you very much! I can install now. windows-build-tools,that is great!

**Comment by ainthek** [comment]
bchr02 : tried your suggested setup, and I still receive #499

**Comment by cjbj** [comment]
@ainthek you'll need to post some real detail about what you actually did. It's impossible for us to guess so we can't really make suggestions about where you may have gone wrong.

**Comment by bchr02** [comment]
I just noticed on windows-build-tools' README.md a section which discusses an important detail about how it installs Python. It reads:
> To not mess with your machine in unnecessary ways, Python is only installed to disk and configured with npm. If you'd like for the python command to work in cmd.exe and PowerShell, add the folder %USERPROFILE%\.windows-build-tools\python27 to your environment variables.

I wonder if it is necessary for those trying to use windows-build-tools to build oracledb to manually type in: ```set PATH=%USERPROFILE%\.windows-build-tools\python27;%PATH%```

Maybe someone here can give it a try and see if it allows them to finally build oracledb?

**Comment by bchr02** [comment]
So here are the revised steps:

Open an elevated CMD prompt (run as Administrator).
navigate to your app folder
```npm install --global npm```
```npm install --global --production windows-build-tools```
```npm install instantclient```
```set PATH=%cd%\instantclient;%USERPROFILE%\.windows-build-tools\python27;%PATH%```
``set OCI_LIB_DIR=%cd%\instantclient\sdk\lib\msvc```
```set OCI_INC_DIR=%cd%\instantclient\sdk\include```
```npm install oracledb```

**Comment by dudleyjosh** [comment]
I am able to install `oracledb` without any issues and I was also about to install `instantclient` via npm, however, I still have the following issue...

```
c:\Users\administrator.ABRASIVE-TECH\Documents\oracledb>node test.js                                                             
c:\Users\administrator.ABRASIVE-TECH\Documents\oracledb\node_modules\oracledb\lib\oracledb.js:38                                 
    throw err;                                                                                                                   
    ^                                                                                                                            
                                                                                                                                 
Error: The specified module could not be found.                                                                                  
\\?\c:\Users\administrator.ABRASIVE-TECH\Documents\oracledb\node_modules\oracledb\build\Release\oracledb.node                    
    at Error (native)                                                                                                            
    at Object.Module._extensions..node (module.js:434:18)                                                                        
    at Module.load (module.js:343:32)                                                                                            
    at Function.Module._load (module.js:300:12)                                                                                  
    at Module.require (module.js:353:17)                                                                                         
    at require (internal/module.js:12:17)                                                                                        
    at Object.<anonymous> (c:\Users\administrator.ABRASIVE-TECH\Documents\oracledb\node_modules\oracledb\lib\oracledb.js:35:19)  
    at Module._compile (module.js:409:26)                                                                                        
    at Object.Module._extensions..js (module.js:416:10)                                                                          
    at Module.load (module.js:343:32)  
```

where `test.js` begins with...

```javascript
var path = require('path');
process.env['PATH'] = path.join(__dirname, '/instantclient') + ';' + process.env['PATH'];
var oracledb = require('oracledb');
```

**Comment by dudleyjosh** [comment]
Ok, I think I finally solved this "Error: The specified module could not be found." issue related to oracledb.node.

I used a free utility called [Dependency Walker](http://www.dependencywalker.com/) to discover that oracledb.node is dependent on MSVCR100.dll which is part of the Visual C++ 2010 SP1 Redistributable Package.

32Bit: Microsoft Visual C++ 2010 SP1 Redistributable Package (x86) 
[http://www.microsoft.com/de-de/download/details.aspx?id=8328](http://www.microsoft.com/de-de/download/details.aspx?id=8328)

64Bit: Microsoft Visual C++ 2010 SP1 Redistributable Package (x64) 
[http://www.microsoft.com/en-us/download/details.aspx?id=13523](http://www.microsoft.com/en-us/download/details.aspx?id=13523)

Once I installed the correct Microsoft Visual C++ 2010 SP1 Redistributable Package it worked fine.

**Comment by cjbj** [comment]
Closing old issue

**Comment by shanetechwiz** [comment]
@bchr02 Thank you so much! You have no idea how much you've helped. Solved a nagging problem for me.

**Comment by bchr02** [comment]
@shanetechwiz you're welcome. Care to share what happened? It might helped others.

**Comment by shanetechwiz** [comment]
@bchr02 Well, it's actually the very same issue that the others were having here

**Comment by cjbj** [comment]
The redistributable is mentioned in INSTALL.md but not until the later section on copying.  I should make it more prominent earlier

> The destination computer's `PATH` needs to include Visual Studio
redistributables.  If you used Oracle client 11.2 then the Visual
Studio 2005 redistributable is required.  For Oracle client 12.1, use
the Visual Studio 2010 redistributable.

**Comment by dudleyjosh** [comment]
@cjbj I think that would be super helpful to call more attention to the need for the VS Redistributables and it would be extra awesome if the direct download links were included in INSTALL.md too. Thanks for clarifying... I definitely missed this critical point multiple times.

**Comment by cjbj** [comment]
@dudleyjosh I committed a change to our internal dev repo (don't ask) the other day, so it will be out with the next drop.

**Comment by CristianDallos** [comment]
bchr02: Excellent Solution. thank you very much.

**Comment by prasadmudedla** [comment]
bchr02: you are awesome man...
Thank you so Much...

**Comment by xftanaka** [comment]
I had a similar problem, but I solved it.
My node version was 8.6.0, but gyp used iojs 1.3.4.
So I forcibly rewritten the code.

`C:\Program Files (x86)\Nodist\npmv\5.5.1\node_modules\node-gyp\lib\process-release.js`

from
` var version = (semver.valid(argv[0]) && argv[0]) || gyp.opts.target || defaultVersion`

to
` var version = defaultVersion`

**Comment by alvinmontano** [comment]
@bchr02 I follow your instructions but still unable to install oracledb and I'm getting this error

gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: unable to get local issuer certificate
gyp ERR! stack     at Error (native)
gyp ERR! stack     at TLSSocket.<anonymous> (_tls_wrap.js:1092:38)
gyp ERR! stack     at emitNone (events.js:86:13)
gyp ERR! stack     at TLSSocket.emit (events.js:185:7)
gyp ERR! stack     at TLSSocket._finishInit (_tls_wrap.js:610:8)
gyp ERR! stack     at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:440:38)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\nodejs\\node.exe" "C:\\Users\\user\\AppData\\Roamin
g\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\user\Desktop\nodeApp\node_modules\oracledb
gyp ERR! node -v v6.11.5
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! oracledb@1.13.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the oracledb@1.13.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\user\AppData\Roaming\npm-cache\_logs\2017-10-26T00_
00_19_076Z-debug.log 

Somebody help me, Thanks in advance

**Comment by alvinmontano** [comment]
I've tried this instructions:

Open an elevated CMD prompt (run as Administrator).
navigate to your app folder
npm install --global npm
npm install --global --production windows-build-tools
npm install instantclient
set PATH=%cd%\instantclient;%PATH%
set OCI_LIB_DIR=%cd%\instantclient\sdk\lib\msvc
set OCI_INC_DIR=%cd%\instantclient\sdk\include
npm install oracledb

but still getting this error

gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: unable to get local issuer certificate
gyp ERR! stack     at Error (native)
gyp ERR! stack     at TLSSocket.<anonymous> (_tls_wrap.js:1092:38)
gyp ERR! stack     at emitNone (events.js:86:13)
gyp ERR! stack     at TLSSocket.emit (events.js:185:7)
gyp ERR! stack     at TLSSocket._finishInit (_tls_wrap.js:610:8)
gyp ERR! stack     at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:440:38)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\nodejs\\node.exe" "C:\\Users\\user\\AppData\\Roamin
g\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\user\Desktop\nodeApp\node_modules\oracledb
gyp ERR! node -v v6.11.5
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! oracledb@1.13.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the oracledb@1.13.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\user\AppData\Roaming\npm-cache\_logs\2017-10-26T00_
00_19_076Z-debug.log

can anybody help me? thanks in advance

**Comment by cjbj** [comment]
@alvinmontano this is a closed issue; better to open new one.  Check the first errors you got: `gyp ERR! stack Error: unable to get local issuer certificate`  Looks like you have a firewall or proxy issue.

**Comment by alvinmontano** [comment]
@cjbj: Thank I will check my proxy setting..
