### ISSUE TITLE
Still can't install on Windows 7

### ISSUE THREAD

**Issue by x10ba** [oracle/node-oracledb#63]
Issue #31 was closed by @cjbj 
however, issue still persists.

updated:

system: windows 7, 64 bit
node version: 0.10.35
python version: 2.7.9
MSVS: 2012

Steps followed:
1.downloaded and extracted both (instantclient-basic-windows.x64-12.1.0.2.0.zip & instantclient-sdk-windows.x64-12.1.0.2.0.zip) to c:\oracle\instantclient

2. set paths for OCI_INC_DIR & OCI_LIB_DIR [as directed] -- also c:\oracle\instantclient

3. ran both in MSVC and outside of MSVC (using vcvars64.bat)

4. npm install oracledb

I get this error:

LINK : fatal error LNK1181: cannot open input file c:\oracle\instantclient\sdk\lib\msvc.obj [c:\node_modules\oracledb\build\oracledb.vcxproj]

Thanks,
x10ba

**Comment by amaruak00** [comment]
+1

**Comment by cjbj** [comment]
@x10ba you will need to give more detail about what you have set variables to, and show things 'dir %OCI_LIB_DIR%' in the dos window you run 'npm install oracledb' in.  Do you have any other Oracle software installed?  

I don't have an immediate solution, so the details are important.

Triple-check you are using 64-bit Node and Instant Client

**Comment by cjbj** [comment]
@amaruak00 Did you mean to "+1" a different feature request issue?

**Comment by amaruak00** [comment]
@cjbj I comented on my Issue: https://github.com/oracle/node-oracledb/issues/59

**Comment by x10ba** [comment]
Hi @cjbj 
Thanks for your help as I really, really want this to work, so I will help as I can.

set via Environment Variables
OCI_LIB_DIR=C:\oracle\instantclient\sdk\lib\msvc
OCI_INC_DIR=C:\oracle\instantclient\sdk\include

Not sure what 'show things' means, can you clarify?

Other software:
c:\oracle\ora90
Toad
Oracle -OraClient11g_home1

**Comment by cjbj** [comment]
@x10ba try the dir command I mentioned; show us what PATH is set to.

Looks like you have a very old version of Oracle installed too.  This could be causing a clash if PATH isn't right.

**Comment by ckjinni** [comment]
@x10ba   same error, me too.

**Comment by cjbj** [comment]
@tminglei isn't that a different error?  It's likely a different cause.  Really looks like OCI_LIB_DIR is not set correctly.

**Comment by tminglei** [comment]
Really? But I already set it according to the guide.
Anyway, I'll try it again.
_Thanks!_

**Comment by tminglei** [comment]
Hi @cjbj,

I still encountered the error. Here's my related system variables:
```
OCI_LIB_DIR=D:\Dev\instantclient_12_1\sdk\lib\msvc
OCI_INC_DIR=D:\Dev\instantclient_12_1\sdk\include
```

p.s. I extracted the `basic`/`sdk` zip files to `D:\Dev\instantclient_12_1`.

_Anything wrong or I missed?_

**Comment by x10ba** [comment]
Hi @cjbj 
Here is my:
'dir %OCI_LIB_DIR%'

directory of c:\oracle\instantclient\sdk\lib\msvc

<DIR>   .
<DIR>  ..
oci.lib
ociw32.lib
oramysql12.lib
oraocci12.lib
oraocci12d.lib
<DIR> vc10
<DIR> vc11
<DIR> vc12

I hope this helps,
Thanks,
x10ba

**Comment by Bigous** [comment]
@tminglei I think that your problem is that you are compiling your software in x64 and the oracle .lib that you are using is x86 or vice-versa.

**Comment by tminglei** [comment]
@Bigous yes, you're right, I used instant client x64 with VS C++ w32.
It was resolved. _Thanks so much!_

**Comment by Bigous** [comment]
@x10ba Does your ORA_LIB_DIR contains an extra space or semicolon at the end?

**Comment by cjbj** [comment]
@Bigous thanks for solving @tminglei's problem.

**Comment by cjbj** [comment]
@x10ba can this be closed now?

**Comment by x10ba** [comment]
Hi,
It still doesn't work for windows, but I will close.
Thanks

X10BA
