### ISSUE TITLE
Uncaught Error: NJS-045: cannot load the oracledb add-on binary for Node.js 7.9.0

### ISSUE THREAD

**Issue by kwent** [oracle/node-oracledb#818]
Hi,

So i spent a fair amount of time trying to make my electron app works. I followed the installation guide with Zip File method but i hit the issue below which prevent the all app to start.

```
Uncaught Error: NJS-045: cannot load the oracledb add-on binary for Node.js 7.9.0 (linux, x64)
Cannot load /home/osboxes/app/release/linux-unpacked/resources/app.asar/node_modules/oracledb/build/Release/oracledb.node
The module '/tmp/.org.chromium.Chromium.QS5Iaa'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 57. This version of Node.js requires
NODE_MODULE_VERSION 54. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or`npm install`).
Node-oracledb installation instructions: https://github.com/oracle/node-oracledb/blob/master/INSTALL.md
You must have 64-bit Oracle client libraries in LD_LIBRARY_PATH, or configured with ldconfig.
If you do not have Oracle Database on this computer, then install the Instant Client Basic or Basic Light package from 
http://www.oracle.com/technetwork/topics/linuxx86-64soft-092277.html
```

The system node version used is v8.2.0. So i have no idea why the error message is mentioning v7.9.0 ?

I installed nvm and switch to 7.9.0 version and same issue.

Not sure about NODE_MODULE_VERSION message as well. 54 is referencing to any nodejs version when i take a look at the official page: https://nodejs.org/en/download/releases/

I tried to rebuild extension but nothing i get stuck with this message. Any idea ?

Regards

**Comment by dmcghan** [comment]
@kwent This line "The module '/tmp/.org.chromium.Chromium.QS5Iaa'..." seems suspect.

What version of Electron are you running?

What version of the driver (node-oracledb) are you using?

What do you get if you run: `console.log(process.versions)`?

Sorry, it's been a while, but when do dependencies of your Electron app get installed/compiled?

You may need to pick your Node.js version, then install Electron, then install the driver. After that, don't change your Node.js version unless you want to reinstall Electron and the driver.

**Comment by kwent** [comment]
@dmcghan  Here is a demo repo i can repro the issue: https://github.com/kwent/electron-react-boilerplate

You can download `.deb` artifact at : https://circleci.com/gh/kwent/electron-react-boilerplate/2#artifacts/containers/0

`circle.yml` is pretty simple and straigforward: https://github.com/kwent/electron-react-boilerplate/blob/master/circle.yml

Let me know what you think...

Regards

**Comment by kwent** [comment]
Alright so it's also happening on OSX and windows.
 
It is because electron 1.7.x (stable release) is using module ABI 54 and none of your precompiled libraries supports it.

How complicated would it be to precompile for module ABI 54 for all platforms your side for all electron users ?

Regards

**Comment by dmcghan** [comment]
@kwent As far as I know, the plan is only to support Node.js versions that have LTS (even numbers). 

I'm kinda surprised Electron is using odd numbers...

Are you unable to compile the binaries? What do you get with this?
`npm install oracle/node-oracledb.git#v2.0.15`

**Comment by dmcghan** [comment]
@kwent I'm happy to look into this more for you, but I'm unable to reproduce with the links you provided. Please provide a script I can use to reproduce (or steps).

**Comment by kwent** [comment]
@dmcghan I'm surprised as well Electron is using odd numbers... but a lot of google results is giving me back `54` for electron `1.7.x` so i might not be the only one.

To repro

```bash
$ git clone git@github.com:kwent/electron-react-boilerplate.git
$ cd app && yarn && cd ..
$ yarn
$ npm run dev (open developer tools to see error message)
```

I'm able having issues building from source cause `yarn`  related to `odpi` lib not found. Work with `npm` but my entired build system is on top of `yarn` and i don't want to change this.

**Comment by kwent** [comment]
@dmcghan  Basically generate precompile binaries for module ABI 54 would fix my issue. Is this something possible to do ?

Regards

**Comment by dmcghan** [comment]
@kwent That script didn't work for me...

Can you upgrade electron? Is the latest version using Node.js 8?

**Comment by kwent** [comment]
Not yet. It’s in beta only for now

**Comment by cjbj** [comment]
There is some info on using yarn with node-oracledb in https://github.com/oracle/node-oracledb/issues/794#issuecomment-344995673

I'd really prefer not to release pre-built binaries for Node 7, since that adds another factor to testing.

**Comment by kwent** [comment]
I'm going to wait for `electron v1.8.2` which should be released shortly and is using NodeJS 8

**Comment by cjbj** [comment]
@kwent good detective work; I'm sure that will help someone.

**Comment by kwent** [comment]
@cjbj The fix needs to be integrated in this lib:

Cf. https://github.com/oracle/node-oracledb/blob/33331413c579e0c3d185a704b4d5862aedaae26e/lib/oracledb.js#L42

**Comment by cjbj** [comment]
@kwent The problem with `require()` seems like a Node.js issue that should be fixed globally in Node.js, no?

**Comment by kwent** [comment]
@cjbj Sure although if we wanna make this library compatible for all nodejs version, we better have another fix here.

It' what `node-sass` ended up doing...

https://github.com/sass/node-sass/pull/2149/files

**Comment by kwent** [comment]
Might actually be another bug... will come back to you after some more tests.

**Comment by kwent** [comment]
I'm actually out of idea. Maybe `trueCasePathSync` would help but i'm not sure...

How can i move forward ? Do you have a windows virtual machine you can help me with to reproduce ?

To repro:

$ git clone git@github.com:kwent/electron-react-boilerplate.git
$ cd electron-react-boilerplate
$ cd app && yarn && cd ..
$ yarn
$ npm run dev (open developer tools to see error message)

Regards

**Comment by kwent** [comment]
I'm still confused. Any help is welcome.

I still don't know if it's coming from this library, or something wrong in the `boilerplate` or even something wrong with `electron`...

**Comment by dtaipov** [comment]
@cjbj I would need a precompiled library for Node.js 7.9.0 (NODE_MODULE_VERSION=51) for Windows. This version of Node is used by electron in VSCode, for which I'm trying to develop an extention using oracledb. According to this [topic](https://github.com/Microsoft/vscode/issues/18253), Node version for electron "cannot be changed" there. I have troubles of complining oracledb from source code because of the proxy issues. What may be an idea to make oracledb work with node 7.9.0?

**Comment by kwent** [comment]
@dtaipov One work around is to upgrade electron to 1.8.2

**Comment by kwent** [comment]
This issue has been fixed with https://github.com/oracle/node-oracledb/pull/851. Closing. Thanks !

**Comment by cjbj** [comment]
@dtaipov If you have proxy issues check out https://oracle.github.io/node-oracledb/INSTALL.html#offline and https://oracle.github.io/node-oracledb/INSTALL.html#github

**Comment by heriipurnama** [comment]
it's work for me.
https://github.com/oracle/node-oracledb/blob/master/INSTALL.md
