### ISSUE TITLE
Erro; NJS-054: Binary build/Release/oracledb.node was not installed.

### ISSUE THREAD

**Issue by gilbertosil** [oracle/node-oracledb#972]
I am trying to install oracledb on a computer with windows 7 and the following problem is occurring:

Answer the following questions:
1. What is your Node.js version? Is it 64-bit or 32-bit? Run version.js from
v10.1.0(64-bits)

2. What is your Oracle client (e.g. Instant Client) version? Is it 64-bit or 32-bit? How was it installed?
Release 10.2.0.5.0

3. What is your Oracle Database version?
12.2.0.1.0

4. What is your OS and version?
windows 7(64 Bits)

5. What is your compiler version? For example, with GCC, run gcc --version
Microsoft Visual C++ 2015 Redistributable(x64)

6. What Oracle environment variables did you set? How exactly did you set them?
none

7. What is the PATH environment variable (on Windows) or LD_LIBRARY_PATH (on Linux) set to? On macOS, what is in ~/lib?
none

8. What exact command caused the problem (e.g. what command did you try to install with)? Who were you logged in as?
npm install -g oracledb

9. What error(s) you are seeing?
![image](https://user-images.githubusercontent.com/1936972/44748982-9fcd4f80-aae7-11e8-84f2-be639317a97e.png)

What can it be ?

**Comment by danilohgds** [comment]
That's from NPM and not from the node module.

Are you behind a firewall? Have you tried the following ?   "npm config set strict-ssl false"

I believe the npm config should fix the problem.

**Comment by gilbertosil** [comment]
@danilohgds 

Yes, we have a firewall in the companyr. About the configuration you commented I already set into my computer.

**Comment by danilohgds** [comment]
@gilbertosil 

The installation covers an http proxy configuration(https://oracle.github.io/node-oracledb/INSTALL.html#instwin) :  

> If you are behind a firewall you may need to set your proxy, for example:
> 
> set http_proxy=http://my-proxy.example.com:80/
> set https_proxy=http://my-proxy.example.com:80/

If it doesnt work, I believe you can force the install with npm install --force and then recompile to your environment with node-gyp, that would generate the binaries which are failing to download.

**Comment by gilbertosil** [comment]
@danilohgds 


I followed the procedure you indicated and the problem still persists. In the company are using the artifactory locally, this may be generating this error?

**Comment by danilohgds** [comment]
@gilbertosil Using force will display the error anyway, but the node-gyp rebuild command will generate the binaries for you, so the library should be usable.

In most configurations, Artifactory, Nexus, and others will not have access to download the binaries, and thus you see the error that you posted.

If you want the binaries to be downloaded, you can consider hosting custom packages on your tool of choice, that means generating an OracleDB ".tgz" file with custom links for your repo.

More details can be found here: https://github.com/oracle/node-oracledb/blob/master/package/README.md

**Comment by gilbertosil** [comment]
I'm closing this issue, becau i think the problem is into my comrpany structure

I tried execute the last example, but the version of oracle client installed into my computer is not supported.

Tks
