### ISSUE TITLE
I`m in trouble with installation.

### ISSUE THREAD

**Issue by StigmaKim** [oracle/node-oracledb#99]
Hi, I have been installed node-oracledb several times, but this time, I encounter new obstacle.

Error message is below.

![error](https://cloud.githubusercontent.com/assets/11647938/7718165/800e46ea-fee7-11e4-94af-92983da55813.jpg)

I installed phyton, visual studio, and set adequate version of node.js.
Please Help me.

Windows7 64bit
nodejs 0.10.38

**Comment by cjbj** [comment]
How did you set the OCI_LIB_DIR and OCI_INC_DIR variables? Did you set them in the system variables, or set them in the command line just before 'npm install oracledb'.  What parts of the installation doc could be improved? https://github.com/oracle/node-oracledb/blob/master/INSTALL.md#instwin

**Comment by RogelioGaytan** [comment]
I have de same problem, i've followed instructions step by step but it's always something that prevents intallation succesfully.

In the install instructions you must add that node-gyp should be installed also. And where in the command prompt you should be located.

Im stuck wit this.


Maybe if hte oracle team made a video making the installation on windows would be very helpful.

Here is my log when i do npm install oracledb


Tiempo transcurrido 00:00:03.39
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "node" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Program Files (x86)\nodejs\node_modules\oracledb
gyp ERR! node -v v0.12.3
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok
npm verb unsafe-perm in lifecycle true
npm info oracledb@0.6.0 Failed to exec install script
npm verb unlock done using C:\Users\Roia\AppData\Roaming\npm-cache\_locks\oracledb-d2d3af7a03f9c6ea.lock for C:\Program Files (x86)\nodejs\node_modules\ora
cledb
npm verb stack Error: oracledb@0.6.0 install: `node-gyp rebuild`
npm verb stack Exit status 1
npm verb stack     at EventEmitter.<anonymous> (C:\Program Files (x86)\nodejs\node_modules\npm\lib\utils\lifecycle.js:213:16)
npm verb stack     at EventEmitter.emit (events.js:110:17)
npm verb stack     at ChildProcess.<anonymous> (C:\Program Files (x86)\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
npm verb stack     at ChildProcess.emit (events.js:110:17)
npm verb stack     at maybeClose (child_process.js:1015:16)
npm verb stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
npm verb pkgid oracledb@0.6.0
npm verb cwd C:\Program Files (x86)\nodejs\node_modules
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "oracledb" "--s
ave" "--verbose"
npm ERR! node v0.12.3
npm ERR! npm  v2.9.1
npm ERR! code ELIFECYCLE

npm ERR! oracledb@0.6.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the oracledb@0.6.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the oracledb package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls oracledb
npm ERR! There is likely additional logging output above.
npm verb exit [ 1, true ]
npm verb unbuild node_modules\oracledb
npm info preuninstall oracledb@0.6.0
npm info uninstall oracledb@0.6.0
npm verb unbuild rmStuff oracledb@0.6.0 from C:\Program Files (x86)\nodejs\node_modules
npm info postuninstall oracledb@0.6.0
npm verb gentlyRm don't care about contents; nuking C:\Program Files (x86)\nodejs\node_modules\oracledb

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Program Files (x86)\nodejs\node_modules\npm-debug.log

C:\Program Files (x86)\nodejs\node_modules>

**Comment by cjbj** [comment]
@RogelioGaytan it would be helpful to see what you actually did & set.

> In the install instructions you must add that node-gyp should be installed also. 

On Linux & OS X this is installed automatically.  I don't recall any Windows users commenting on this needing to be installed separately?

> And where in the command prompt you should be located.

Good point.  Although it may not matter which directory, ambiguity in instructions is always disconcerting.

> Maybe if hte oracle team made a video making the installation on windows would be very helpful.

That sounds like a great idea for someone in the community to do (@bchr02 @bigous? @kgajowy? @scottchantry? @amaruak00? Any other windows user?)

**Comment by StigmaKim** [comment]
I'm sorry It is resolved long time ago. I forgot to record it.

In my case, that message is a result that the OCI_LIB_DIR and OCI_INC_DIR variables didn't set.

After set the OCI_LIB_DIR and OCI_INC_DIR, error message is gone, and It works perfectly.

**Comment by cjbj** [comment]
@StigmaKim Thanks - glad you got it going.

@RogelioGaytan It's best to open your own issue if you still have problems.

**Comment by Bigous** [comment]
Hi @cjbj, about the suggestion of making a video, I think this is a good idea, I don't have much time to do, but i think it's better to make the pre-compiled packages as issue #18 is purposing.
It would be just an "npm install oracledb" to have it working on any platform that the compiler is not available.

**Comment by RogelioGaytan** [comment]
Thaks to every one, i set those variables in te command line, i'll try doing it from de system variables and see what happens. If i still have problems i'll make a new issue post

**Comment by StigmaKim** [comment]
Good Luck @RogelioGaytan.

**Comment by bchr02** [comment]
@StigmaKim, @RogelioGaytan, @Bigous Since there have been some requests for a video, demonstrating the installation of oracledb on Windows, I created one: [Video - install of oracledb on Windows 7 x64](https://www.youtube.com/watch?v=uZbNS2yLmjo)

**Comment by Bigous** [comment]
Nice! Good Job :dart: @bchr02 

I think we should consider researching and making some inputs to have oracledb installed on any platform without the compilation step (just like phantomjs does) as you stated at #18

**Comment by bchr02** [comment]
Thanks @Bigous. I agree with you. I will make an update to #18 with a suggestion as to how we can proceed.

**Comment by RogelioGaytan** [comment]
Thank you for your apportation to the community @bchr02
